baseURL = "https://sergioaafreitas.github.io/COMP1/"
languageCode = "pt-br"
title = "CEDIS / UnB - Compiladores 1"
theme = "doks"

# Outras configurações recomendadas pelo Doks
[params]
  description = "Repositório de materiais acadêmicos"
  author = "Seu Nome"
  github = "https://github.com/seu-usuario"

[menu]
  [[menu.main]]
    name = "Início"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Materiais"
    url = "/materiais/"
    weight = 2
